Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder "./", "/home/vagrant/"

  # config.vm.provider "virtualbox" do |vb|
  #   vb.gui = false
  #   vb.memory = "4096"
  #
  #   vb.customize [
  #     "modifyvm", :id,
  #     "--vram", "256", # フルスクリーンモード用
  #     "--clipboard", "bidirectional", # クリップボード共有
  #     "--draganddrop", "bidirectional", # ドラッグアンドドロップ
  #     "--cpus", "2",
  #     "--ioapic", "on" # I/O APICを有効化
  #   ]
  # end

  # You neee sudo using 'xpm'
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    echo "node/npm/xpm"
    wget https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.xz
    tar -xvf ./node-v18.12.1-linux-x64.tar.xz
    rm -f ./node-v18.12.1-linux-x64.tar.xz
    ln -s /home/vagrant/node-v18.12.1-linux-x64/bin/node /usr/local/bin/node
    ln -s /home/vagrant/node-v18.12.1-linux-x64/bin/npm /usr/local/bin/npm
    npm install --global xpm@latest

    echo "Arm Toolchain"
    xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@latest

    echo "RISC-V Toolchain"

    echo "SEGGER j-Link"
    echo "You need set [deb file] before provision"
    echo "Link: https://www.segger.com/downloads/jlink/#J-LinkSoftwareAndDocumentationPack"
    dpkg -i [deb file]

    echo "OpenOCD"
    xpm install --global @xpack-dev-tools/openocd@latest

    echo "QEMU Arm"
    xpm install --global @xpack-dev-tools/qemu-arm@latest

    echo "Java"
    wget https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_linux-x64_bin.tar.gz
    tar -xvf ./openjdk-15.0.2_linux-x64_bin.tar.gz
    rm -f ./openjdk-15.0.2_linux-x64_bin.tar.gz
    ln -s /home/vagrant/jdk-15.0.2/bin/java /usr/local/bin/java
    java --version

    echo "###########################"
    echo "# Eclipse Install & Setup #"
    echo "###########################"
  SHELL
end
